POSTGRES_USERNAME = ENV['POSTGRES_USERNAME']
POSTGRES_PASSWORD = ENV['POSTGRES_PASSWORD']
DATABASE_NAME = ENV['DATABASE_NAME']
DATABASE_HOST = ENV['DATABASE_HOST']
DATABASE_PORT = ENV['DATABASE_PORT']

DB = Sequel.connect("postgres://#{POSTGRES_USERNAME}:#{POSTGRES_PASSWORD}@#{DATABASE_HOST}:#{DATABASE_PORT}/#{DATABASE_NAME}")
DB.extension(:pagination)
